// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlamoeniqvncexayrttl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsYW1vZW5pcXZuY2V4YXlydHRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODkwOTMsImV4cCI6MjA1ODQ2NTA5M30.DvZOPqws_bEpZ_Ps-i9O6vjlEKeyk--t4vbaKXXcwKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);